Sistema_Iglesia/urls.py
from django.urls import include, path, re_path, reverse_lazy
from django.contrib import admin
admin.site.site_url = '/portada/index'
from django.contrib.auth import views
from apps.persona import views
from apps.ministerio import views
from apps.usuario import views
from apps.evento import views
from apps.movimiento_dinero import views
from apps.celula import views
from apps.discipulado import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetView, PasswordResetCompleteView, PasswordResetConfirmView, PasswordChangeView, PasswordChangeDoneView, PasswordResetDoneView #login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from apps.usuario.views import RegistroUsuario
from apps.portada import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'authapp'

urlpatterns = [
    #url(r'^admin/', admin.site.urls, name='administrar'),
    re_path(r'^admin/', admin.site.urls, name='administrar'),
    re_path(r'^persona/', include(('apps.persona.urls', 'persona'), namespace='persona')),
    #url(r'^matrimonio/', include('apps.persona.urls', namespace='matrimonio')),
    re_path(r'^movimiento/', include(('apps.movimiento_dinero.urls', 'movimiento_dinero'), namespace='movimiento')),
    #url(r'^categoria/', include('apps.movimiento_dinero.urls', namespace='categoria')),
    re_path(r'^ministerio/', include(('apps.ministerio.urls', 'ministerio'), namespace='ministerio')),
    re_path(r'^evento/', include(('apps.evento.urls', 'evento'), namespace='evento')),
    re_path(r'^celula/', include(('apps.celula.urls', 'celula'), namespace='celula')),
    re_path(r'^articulo/', include(('apps.inventario.urls', 'inventario'), namespace='articulo')),
    #url(r'^unidad_de_medida/', include('apps.inventario.urls', namespace='unidad_de_medida')),
    re_path(r'^entrada/', include(('apps.entrada.urls', 'entrada'), namespace='entrada')),
    re_path(r'^salida/', include(('apps.salida.urls', 'salida'), namespace='salida')),
    re_path(r'^entradasalida/', include(('apps.entradasalida.urls', 'entradasalida'), namespace='entradasalida')),
    re_path(r'^portada/', include(('apps.portada.urls', 'portada'), namespace='portada')),
    re_path(r'^discipulado/', include(('apps.discipulado.urls', 'discipulado'), namespace='discipulado')),
    re_path(r'^portada/', include(('apps.portada.urls','portada'), namespace='portada')),
    re_path(r'^usuario/', include(('apps.usuario.urls', 'usuario'), namespace='usuario')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
#    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'), -----Django 1.8
#    url(r'^logout/', logout_then_login, name='logout'),
    #re_path(r'^accounts/login/$', LoginView.as_view(template_name='index.html'), name='login'), #-----Django 3.1.4
    #re_path(r'^logout/$', LogoutView.as_view(), name='logout'), #-----Django 3.1.4

    re_path(r'^accounts/login/$', LoginView.as_view(template_name='index.html'), name='login'),
    re_path(r'^accounts/logout/$', LogoutView.as_view(template_name='portada/post_list.html'), name='logout'),
    re_path(r'^password_change/', PasswordChangeView.as_view(
        template_name='registration/password_change_form.html'), name='password_change'),
    re_path(r'^password_change/done/', PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),
    re_path(r'^reset/password_reset', PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        email_template_name='registration/password_reset_email.html'), name='password_reset'),
    re_path(r'^password_reset_done', PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'), name='password_reset_done'),

    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',), name='password_reset_confirm'),

    re_path(r'^reset/done', PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'), name='password_reset_complete'),




    #url(r'^password/recovery/',
	#	RegistroUsuario.as_view(
	#		template_name='restration/password_reset_form.html',
	#		email_template_name='restration/password_reset_email.html',
	#	),
	#	name='password_reset',
	#	),
#    re_path(r'^reset/password_reset', PasswordResetView.as_view(),
#        {'template_name':'registration/password_reset_form.html',
#        'email_template_name': 'registration/password_reset_email.html'},
#        name='password_reset'),

#    re_path(r'^password_reset_done', PasswordResetDoneView.as_view(),
#        {'template_name': 'registration/password_reset_done.html'},
#        name='password_reset_done'),

#    re_path(r'^password/recovery/(?P<uidb64>[0-9A-Za-z_\-]+)/'
#        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', PasswordResetConfirmView.as_view(),
#        {'template_name': 'registration/password_reset_confirm.html'},
#        name='password_reset_confirm'),

    # url(
    #    r'^password/recovery/(?P<uidb64>[0-9A-Za-z_\-]+)/'
    #    r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #    auth_views.PasswordResetConfirmView.as_view(
    #        success_url=reverse_lazy('home'),
    #        post_reset_login=True,
    #        template_name='registration/password_reset_confirm.html',
    #        post_reset_login_backend=(
    #            'django.contrib.auth.backends.AllowAllUsersModelBackend'
    #        ),
    #    ),
    #    name='password_reset_confirm',
    #),

#    re_path(r'^reset/done', PasswordResetCompleteView, {'template_name': 'registration/password_reset_complete.html'},
#        name='password_reset_complete'),




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/discipulado/urls.py
from django.urls import include, path, re_path
from django.contrib.auth.views import login_required
from apps.discipulado import views
from apps.discipulado.views import discipulado_view, discipulado_list, discipulado_edit, discipulado_delete,\
     discipulado_list_baja , discipulado_restore,buscar_discipulador_discipulado, buscar_persona_discipulado

urlpatterns = [
    re_path(r'^discipulado/listar$', views.discipulado_list, name='discipulado_listar'),
    re_path(r'^discipulado/nueva$', views.discipulado_view, name='discipulado_crear'),
    re_path(r'^discipulado/editar/(?P<pk>\d+)$', views.discipulado_edit, name='discipulado_editar'),
    re_path(r'^discipulado/eliminar/(?P<pk>\d+)$', views.discipulado_delete, name='discipulado_eliminar'),
    re_path(r'^discipulado/listar/baja/$', views.discipulado_list_baja , name='discipulado_listar_baja'),
	re_path(r'^discipulado/restaurar/(?P<pk>\d+)/$', views.discipulado_restore , name='discipulado_restaurar'),
    #url(r'^buscar/$', BuscarView.as_view(),name='discipulado_buscar'),
    re_path(r'^discipulado/buscardiscipulador/$', views.buscar_discipulador_discipulado, name='buscardiscipulador'),
    re_path(r'^discipulado/buscarpersonadicipulada/$', views.buscar_persona_discipulado, name='buscarpersonadicipulada'),
]

apps/discipulado/models.py
from django.db import models
#from apps.validators import persona_validation
from django.core.exceptions import ValidationError
# Create your models here.
from apps.persona.models import Persona

#class Discipulador(models.Model):
#    nombre_discipulador = models.CharField(max_length=50)#ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    #id_persona =models.ForeignKey(Persona, null=True, blank=True, related_name="personaDiscipulada", on_delete=models.CASCADE)

#    def __str__(self):
#        return self.nombre_discipulador

class Discipulado(models.Model):
    nombre_material_discipulado = models.CharField(max_length=50, blank=False, null = False)
    discipulador = models.ForeignKey(Persona, blank=False, null = False, related_name="personaDiscipuladora", on_delete=models.CASCADE)
    persona = models.ForeignKey(Persona, blank=False, null = False, related_name="personaDiscipulada", on_delete=models.CASCADE)#, validators=[persona_validation])
    fecha_fin = models.CharField(max_length=10,null=True, blank=True)
    fecha_baja_discipulado = models.DateField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.nombre_material_discipulado

    class Meta:
                permissions = (('ver_detalle_discipulado', 'Ver detalle discipulados'),)
                unique_together = ('discipulador', 'persona',)
    def clean(self):
            if self.discipulador == self.persona:
                raise ValidationError('Error: el discípulo y el discipulador no pueden ser la misma persona.')

apps/discipulado/forms.py
from django import forms

from apps.discipulado.models import Discipulado#, Discipulador
from apps.persona.models import Persona

class DiscipuladosForm(forms.ModelForm):
    persona = forms.ModelChoiceField(queryset=Persona.objects.filter(fecha_baja_persona__isnull=True))
    discipulador = forms.ModelChoiceField(queryset=Persona.objects.filter(fecha_baja_persona__isnull=True))

    def __init__(self, *args, **kwargs):
        super(DiscipuladosForm, self).__init__(*args, **kwargs)
        self.fields['persona'].label = "Persona Discipulada"

    class Meta:
        model = Discipulado

        fields = [
            'nombre_material_discipulado',
            'discipulador',
            'persona',
            'fecha_fin',
        ]
        labels = {
            'nombre_material_discipulado': 'Nombre del material',
            'discipulador': 'Discipulador',
            'persona': 'Persona discipulada',
            'fecha_fin': 'Fecha fin discipulado',
        }

"""class DiscipuladoresForm(forms.ModelForm):

    class Meta:
        model = Discipulador

        fields = [
        #    'nombre_discipulador',
            'id_persona',
        ]
        labels = {
        #    'nombre_discipulador': 'Nombre discipulador',
            'id_persona': 'Nombre discipulador',

        }
"""

apps/discipulado/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
import datetime
from apps.discipulado.models import Discipulado#, Discipulador
from apps.discipulado.forms import DiscipuladosForm#, DiscipuladoresForm
from apps.persona.models import Persona
from django.contrib.auth.decorators import login_required
from django.db.models import Q

###################   					DISCIPULADOS


@login_required
def discipulado_view(request):
    if request.method == 'POST':
        form = DiscipuladosForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('discipulado:discipulado_listar')
    else:
        form = DiscipuladosForm
    return render(request, 'discipulado/discipulado_form.html', {'form':form})

@login_required
def discipulado_list(request):
	discipulado = Discipulado.objects.filter(fecha_baja_discipulado__isnull=True)
	contexto = {'discipulados':discipulado}
	return render(request, 'discipulado/discipulado_listar.html', contexto)

@login_required
def get_queryset_discipulado(self):
    queryset = Discipulado.objects.filter(fecha_baja_discipulado__isnull=True).order_by('nombre_material_discipulado')#
    return queryset

@login_required
def discipulado_list_baja(request):
	discipulado = Discipulado.objects.filter(fecha_baja_discipulado__isnull=False)
	contexto = {'discipulados':discipulado}
	return render(request, 'discipulado/discipulado_listar_baja.html', contexto)

@login_required
def discipulado_restore(request, pk):
    discipulado = Discipulado.objects.get(id=pk)
    if request.method == 'GET':
        discipulado.fecha_baja_discipulado = None
        discipulado.save()
        return redirect('discipulado:discipulado_listar_baja')
    return redirect('discipulado:discipulado_listar')

@login_required
def discipulado_edit(request, pk):
    discipulado = Discipulado.objects.get(id=pk)
    if request.method == 'GET':
        form = DiscipuladosForm(instance=discipulado)
    else:
        form = DiscipuladosForm(request.POST, instance=discipulado)
        if form.is_valid():
            form.save()
            return redirect('discipulado:discipulado_listar')
    return render(request,'discipulado/discipulado_form.html',{'form':form})

@login_required
def discipulado_delete(request, pk):
	discipulado = Discipulado.objects.get(id=pk)
	if request.method == 'POST':
		discipulado.fecha_baja_discipulado = datetime.date.today()
		discipulado.save()
		return redirect('discipulado:discipulado_listar')
	return render(request,'discipulado/discipulado_delete.html',{'discipulado':discipulado})

@login_required
def buscar_discipulador_discipulado(request):
    query = request.GET.get('q')
    if query is not None and query != ' ' and request.is_ajax():
        discipulados = get_queryset_discipulado(request).filter(Q(discipulador__nombre__icontains=query)|Q(discipulador__apellido_persona__icontains=query))
        return render(request, 'discipulado/buscar_discipulado.html', {'discipulados': discipulados})
    discipulados =  get_queryset_discipulado(request)
    return render(request, 'discipulado/buscar_discipulado.html', {'discipulados': discipulados})

@login_required
def buscar_persona_discipulado(request):
    query = request.GET.get('q')
    if query is not None and query != ' ' and request.is_ajax():
        discipulados = get_queryset_discipulado(request).filter(Q(persona__nombre__icontains=query)|Q(persona__apellido_persona__icontains=query))
        return render(request, 'discipulado/buscar_discipulado.html', {'discipulados': discipulados})
    discipulados =  get_queryset_discipulado(request)
    return render(request, 'discipulado/buscar_discipulado.html', {'discipulados': discipulados})

#class BuscarView(TemplateView):
#	def post(self, request, *args, **kwargs):
#		buscar = request.POST['buscalo']
#		dis1 = Discipulado.objects.filter(nombre_material_discipulado__icontains=buscar)
#		dis2 = Discipulado.objects.filter(discipulador__nombre__icontains=buscar)
#		dis3 = Discipulado.objects.filter(persona__nombre__icontains=buscar)
#		dis4 = Discipulado.objects.filter(fecha_fin__icontains=buscar)
#		contexto = {
#		'discipulados1':dis1,
#		'discipulados2':dis2,
#		'discipulados3':dis3,
#		'discipulados4':dis4,
#		}
#		return render(request,'discipulado/buscar.html', contexto)

templates/discipulado/buscar.html
{% extends 'base/base.html' %}

{% block content %}

<!--boton buscar ---->
<div class = "busqueda">
	<form class = "navbar-search pull-left" method
	="POST" action="/discipulado/buscar/">{% csrf_token %}

		<input type="text" name="buscalo" class="search-query"
		placeholder="Buscar">
		<div class="btn-group">
				<button class="btn btn-primary" type
				="sumbit"><i class="icon-search"></i
				></button>
		</div>
	</form>
</div>
<!--fin boton buscar ---->

<table class="table table-bordered">
	<thead>
		<tr>
			<th>Nombre del material</th>
			<th>Discipulador</th>
			<th>Discípulo</th>
			<th>Fecha fin discipulado</th>
		</tr>
	</thead>
	<tbody>
		{% if discipulados1 %}
		{% for dis1 in discipulados1 %}
		<tr>
			<td>{{ dis1.nombre_material_discipulado }}</td>
			<td>{{ dis1.discipulador }}</td>
			<td>{{ dis1.persona }}</td>
			<td>{{ dis1.fecha_fin }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'discipulado:discipulado_editar' dis1.id%}">Editar</a>
				<a class="btn btn-danger" href="{% url 'discipulado:discipulado_eliminar' dis1.id%}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		{% elif discipulados2 %}
		{% for dis2 in discipulados2 %}
		<tr>
			<td>{{ dis2.nombre_material_discipulado }}</td>
			<td>{{ dis2.discipulador  }}</td>
			<td>{{ dis2.persona  }}</td>
			<td>{{ dis2.fecha_fin }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'discipulado:discipulado_editar' dis2.id%}">Editar</a>
				<a class="btn btn-danger" href="{% url 'discipulado:discipulado_eliminar' dis2.id%}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		{% elif discipulados3 %}
		{% for dis3 in discipulados3 %}
		<tr>
			<td>{{ dis3.nombre_material_discipulado }}</td>
			<td>{{ dis3.discipulador  }}</td>
			<td>{{ dis3.persona  }}</td>
			<td>{{ dis3.fecha_fin }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'discipulado:discipulado_editar' dis3.id%}">Editar</a>
				<a class="btn btn-danger" href="{% url 'discipulado:discipulado_eliminar' dis3.id%}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		{% elif discipulados4 %}
		{% for dis4 in discipulados4 %}
		<tr>
			<td>{{ dis4.nombre_material_discipulado }}</td>
			<td>{{ dis4.discipulador }}</td>
			<td>{{ dis4.persona }}</td>
			<td>{{ dis4.fecha_fin }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'discipulado:discipulado_editar' dis4.id%}">Editar</a>
				<a class="btn btn-danger" href="{% url 'discipulado:discipulado_eliminar' dis4.id%}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		{% else %}
		<h1>No hay discipulados registrados</h1>
		{% endif %}
  	</tbody>
  </table>
  <ul class="pager">
  	<li>
  		{% if page_obj.has_previous %}
         	 <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>

  		{% endif %}
    </li>
  	<li>
  		{% if page_obj.has_next %}
       	 <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>

      	{% endif %}
    </li>
  </ul>

  {% endblock%}

templates/discipulado/buscar_discipulado.html
{% if discipulados %}
{% for discipulado in discipulados %}
<tr>
  <td>{{ discipulado.nombre_material_discipulado }}</td>
  <td>{{ discipulado.discipulador }}</td>
  <td>{{ discipulado.persona }}</td>
  <td>{{ discipulado.fecha_fin }}</td>
  {%block campobajadiscipulado%}
  {%endblock%}
  <td>
    {% if discipulado.fecha_baja_discipulado == null %}
      {% if perms.discipulado.change_discipulado %}
        <a class="btn btn-primary" style="width: 80px; line-height: 5px;padding: 10px;" href="{% url 'discipulado:discipulado_editar' discipulado.id%}">Editar</a>
      {% endif %}
      {% if perms.discipulado.delete_discipulado %}
        <a class="btn btn-danger" style="width: 80px; line-height: 5px;padding: 10px;" href="{% url 'discipulado:discipulado_eliminar' discipulado.id%}">Eliminar</a>
      {% endif %}
    {%endif%}
    {%block pruebadiscipulado%}
    {%endblock%}
  </td>
</tr>
{% endfor %}

{% else %}
  <td colspan="13">
    No hay discipulados
  </td>
{% endif %}

templates/discipulado/discipulado_delete.html
{% extends 'base/base.html' %}

{% block content %}
	{% if perms.discipulado.delete_discipulado %}
		<form style="margin: 80px auto auto 20px" method="post">
			{% csrf_token %}
			<h3>¿Desea eliminar el discipulado de {{ discipulado.persona.nombre}} {{ discipulado.persona.apellido_persona}}?</h3>
			<button class="btn btn-danger" style="line-height: 15px" type="submit">Sí, eliminar</button>
			<a class= "btn btn-default" style="line-height: 15px" href="{% url 'discipulado:discipulado_listar' %}">Cancelar</a>
		</form>
	{% endif %}
{% endblock %}

templates/discipulado/discipulado_form.html
{% extends 'base/base.html' %}

{% block title %}
	Discipulados
{% endblock %}

{% block content %}
	{% if perms.discipulado.add_discipulado %}
	<h2>Registrar discipulado:</h2>
		<div class="mb-2">
			<form autocomplete="off" method="post">
				{% csrf_token %}
				{% include 'includes/form.html' %}
				<div style="float: left; margin: 27px 17px;">
					<button class="btn btn-success" style="line-height: 15px" type="submit">Registrar</button>
					<a class="btn btn-danger" style="line-height: 15px" href="{% url 'discipulado:discipulado_listar' %}">Cancelar</a>
				</div>
			</form>
		</div>
	{% endif %}
{% endblock %}

{% block extrajs %}
	<script>
		$('#id_fecha_fin').datepicker({
			todayBtn: "linked",
			format: 'dd-mm-yyyy',
			endDate: '0d',
			language: 'es',
		})
	</script>
{% endblock %}

templates/discipulado/discipulado_listar.html
{% extends 'base/base.html' %}
{% block title %}
	Detalle de Discipulados
{% endblock %}

{% block content %}

<!--boton buscar -->
<!--
<div class = "busqueda">
	<form class = "navbar-search pull-left" method
	="POST" action="/discipulado/buscar/">{% csrf_token %}

		<input type="text" name="buscalo" class="search-query"
		placeholder="Buscar">
		<div class="btn-group">
				<button class="btn btn-primary" type
				="sumbit"><i class="icon-search"></i
				></button>
		</div>
	</form>
</div>
<!--fin boton buscar -->
{%block encabezado%}
	<h2>Discipulados:</h2>
{%endblock%}
{% block buscardiscupulado %}
<div id="contenedor" >
	<th>Buscar: </th>
			<input class="form-control-sm" id="buscar-discipulador" type="text" placeholder="Discipulador"/>
      <input class="form-control-sm" id="buscar-persona" type="text" placeholder="Discípulo"/>
</div>
{%endblock%}
<h1></h1>
<table id="contenedor" class="table table-bordered table-hover">
	<thead>
		<tr>
			<th>Nombre del material</th>
			<th>Discipulador</th>
			<th>Discípulo</th>
			<th>Fecha fin discipulado</th>
			{%block titulobaja%}
			{%endblock%}
			<th>Opciones</th>
		</tr>
	</thead>
	<tbody id="resultado-busqueda">
	</tbody>
	<tbody id="main">
		{% if discipulados %}
		{% for discipulado in discipulados %}
		<tr>
			<td>{{ discipulado.nombre_material_discipulado |title }}</td>
			<td>{{ discipulado.discipulador |title }}</td>
			<td>{{ discipulado.persona |title }}</td>
			<td>{{ discipulado.fecha_fin }}</td>
			{%block campobajadiscipulado%}
			{%endblock%}
			<td>
				{% if discipulado.fecha_baja_discipulado == null %}
					{% if perms.discipulado.change_discipulado %}
						<a class="btn btn-primary" style="width: 80px; line-height: 5px;padding: 10px;" href="{% url 'discipulado:discipulado_editar' discipulado.id%}">Editar</a>
					{% endif %}
					{% if perms.discipulado.delete_discipulado %}
						<a class="btn btn-danger" style="width: 80px; line-height: 5px;padding: 10px;" href="{% url 'discipulado:discipulado_eliminar' discipulado.id%}">Eliminar</a>
					{% endif %}
				{%endif%}
				{%block pruebadiscipulado%}
				{%endblock%}
			</td>
		</tr>
		{% endfor %}

		{% else %}
		<td colspan="13">
				No hay discipulados
			</td>
		{% endif %}
	</tbody>
</table>
<ul id="contenedor" class="pager">
	<li>
		{% if page_obj.has_previous %}
       	 <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
		{% endif %}
  </li>
	<li>
		{% if page_obj.has_next %}
     	 <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
    	{% endif %}
  </li>
</ul>

{% block botonfinaldiscipulado %}
	{% if perms.discipulado.delete_discipulado %}
		<a id="contenedor" class="btn btn-danger" style="line-height: 15px" href="{% url 'discipulado:discipulado_listar_baja' %}">Ver  registros eliminados</a>
	{% endif %}
{%endblock%}
{% endblock%}
{% block extrajs %}
<script>
$('#buscar-discipulador').keyup(function (event) {
	var query =($('#buscar-discipulador').val());
	if ( $.trim( $('#buscar-discipulador').val() ) != '' ) {
		ajax(query,"buscardiscipulador/");
		esconderMain();
	}
	else {
		mostrarMain();
	}
});

$('#buscar-persona').keyup(function (event) {
  var query =($('#buscar-persona').val());
  if ( $.trim( $('#buscar-persona').val() ) != '' ) {
		ajax(query,"buscarpersonadicipulada/");
		esconderMain();
  }
  else {
		mostrarMain();
  }
});


function mostrarMain(){
$('#resultado-busqueda').hide();
$('#main').show("slow");
}
function esconderMain(){
$('#resultado-busqueda').show("slow");
$('#main').hide();
}

function ajax(query,url){
console.log(query);
$.ajax({
	 type: 'GET',
	 url: url,
	 data: {
		 'csrfmiddlewaretoken': '{{ csrf_token }}',
		 'q': query,
	 },
	 success: function(data) {
		 console.log(data);
			$('#resultado-busqueda').html(data);
	 },
	 error: function(data) {
			console.log(data);
	 }
 });
}

</script>

{% endblock %}

templates/discipulado/discipulado_listar_baja.html
{% extends 'discipulado/discipulado_listar.html' %}
{% if perms.discipulado.add_discipulado %}

	{%block encabezado%}
		<h2>Discipulados dados de baja:</h2>
	{%endblock%}

	{%block titulobajadiscipulado%}
		<th>Fecha Baja</th>
	{%endblock%}

	{%block campobajadiscipulado%}
		<td>{{ discipulado.fecha_baja_discipulado }}</td>
	{%endblock%}

	{%block pruebadiscipulado%}
		<a class="btn btn-primary" style="line-height: 15px" href="{% url 'discipulado:discipulado_restaurar' discipulado.id%}">Restaurar</a>
	{%endblock%}

	{% block botonfinaldiscipulado %}
		<a id="contenedor" class="btn btn-default" style="line-height: 15px" href="{% url 'discipulado:discipulado_listar' %}">Volver</a>
	{% endblock%}

	{% block buscardiscupulado %}
	{% endblock%}
{% endif %}