Sistema_Iglesia/urls.py
from django.urls import include, path, re_path, reverse_lazy
from django.contrib import admin
admin.site.site_url = '/portada/index'
from django.contrib.auth import views
from apps.persona import views
from apps.ministerio import views
from apps.usuario import views
from apps.evento import views
from apps.movimiento_dinero import views
from apps.celula import views
from apps.discipulado import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetView, PasswordResetCompleteView, PasswordResetConfirmView, PasswordChangeView, PasswordChangeDoneView, PasswordResetDoneView #login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from apps.usuario.views import RegistroUsuario
from apps.portada import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'authapp'

urlpatterns = [
    #url(r'^admin/', admin.site.urls, name='administrar'),
    re_path(r'^admin/', admin.site.urls, name='administrar'),
    re_path(r'^persona/', include(('apps.persona.urls', 'persona'), namespace='persona')),
    #url(r'^matrimonio/', include('apps.persona.urls', namespace='matrimonio')),
    re_path(r'^movimiento/', include(('apps.movimiento_dinero.urls', 'movimiento_dinero'), namespace='movimiento')),
    #url(r'^categoria/', include('apps.movimiento_dinero.urls', namespace='categoria')),
    re_path(r'^ministerio/', include(('apps.ministerio.urls', 'ministerio'), namespace='ministerio')),
    re_path(r'^evento/', include(('apps.evento.urls', 'evento'), namespace='evento')),
    re_path(r'^celula/', include(('apps.celula.urls', 'celula'), namespace='celula')),
    re_path(r'^articulo/', include(('apps.inventario.urls', 'inventario'), namespace='articulo')),
    #url(r'^unidad_de_medida/', include('apps.inventario.urls', namespace='unidad_de_medida')),
    re_path(r'^entrada/', include(('apps.entrada.urls', 'entrada'), namespace='entrada')),
    re_path(r'^salida/', include(('apps.salida.urls', 'salida'), namespace='salida')),
    re_path(r'^entradasalida/', include(('apps.entradasalida.urls', 'entradasalida'), namespace='entradasalida')),
    re_path(r'^portada/', include(('apps.portada.urls', 'portada'), namespace='portada')),
    re_path(r'^discipulado/', include(('apps.discipulado.urls', 'discipulado'), namespace='discipulado')),
    re_path(r'^portada/', include(('apps.portada.urls','portada'), namespace='portada')),
    re_path(r'^usuario/', include(('apps.usuario.urls', 'usuario'), namespace='usuario')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
#    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'), -----Django 1.8
#    url(r'^logout/', logout_then_login, name='logout'),
    #re_path(r'^accounts/login/$', LoginView.as_view(template_name='index.html'), name='login'), #-----Django 3.1.4
    #re_path(r'^logout/$', LogoutView.as_view(), name='logout'), #-----Django 3.1.4

    re_path(r'^accounts/login/$', LoginView.as_view(template_name='index.html'), name='login'),
    re_path(r'^accounts/logout/$', LogoutView.as_view(template_name='portada/post_list.html'), name='logout'),
    re_path(r'^password_change/', PasswordChangeView.as_view(
        template_name='registration/password_change_form.html'), name='password_change'),
    re_path(r'^password_change/done/', PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),
    re_path(r'^reset/password_reset', PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        email_template_name='registration/password_reset_email.html'), name='password_reset'),
    re_path(r'^password_reset_done', PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'), name='password_reset_done'),

    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',), name='password_reset_confirm'),

    re_path(r'^reset/done', PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'), name='password_reset_complete'),




    #url(r'^password/recovery/',
	#	RegistroUsuario.as_view(
	#		template_name='restration/password_reset_form.html',
	#		email_template_name='restration/password_reset_email.html',
	#	),
	#	name='password_reset',
	#	),
#    re_path(r'^reset/password_reset', PasswordResetView.as_view(),
#        {'template_name':'registration/password_reset_form.html',
#        'email_template_name': 'registration/password_reset_email.html'},
#        name='password_reset'),

#    re_path(r'^password_reset_done', PasswordResetDoneView.as_view(),
#        {'template_name': 'registration/password_reset_done.html'},
#        name='password_reset_done'),

#    re_path(r'^password/recovery/(?P<uidb64>[0-9A-Za-z_\-]+)/'
#        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', PasswordResetConfirmView.as_view(),
#        {'template_name': 'registration/password_reset_confirm.html'},
#        name='password_reset_confirm'),

    # url(
    #    r'^password/recovery/(?P<uidb64>[0-9A-Za-z_\-]+)/'
    #    r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #    auth_views.PasswordResetConfirmView.as_view(
    #        success_url=reverse_lazy('home'),
    #        post_reset_login=True,
    #        template_name='registration/password_reset_confirm.html',
    #        post_reset_login_backend=(
    #            'django.contrib.auth.backends.AllowAllUsersModelBackend'
    #        ),
    #    ),
    #    name='password_reset_confirm',
    #),

#    re_path(r'^reset/done', PasswordResetCompleteView, {'template_name': 'registration/password_reset_complete.html'},
#        name='password_reset_complete'),




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/celula/urls.py
from django.urls import include, path, re_path
from django.contrib.auth.views import login_required
from apps.celula import views
from apps.celula.views import celula_view, celula_list, celula_edit, \
celula_delete, celula_list_baja, celula_restore, BuscarView, celula_agregar_miembros, \
miembros_celula_list, miembros_celula_delete, miembros_celula_list_baja, buscar_dia_celula, buscar_encargado_celula

urlpatterns = [
    re_path(r'^celula/nueva$', views.celula_view , name='celula_crear'),
    re_path(r'^celula/listar$', views.celula_list , name='celula_listar'),
    re_path(r'^celula/editar/(?P<pk>\d+)$', views.celula_edit , name='celula_editar'),
    re_path(r'^celula/eliminar/(?P<pk>\d+)$', views.celula_delete , name='celula_eliminar'),
    re_path(r'^celula/listar/agregar/$', views.celula_agregar_miembros , name='celula_agregar_miembros'),
    re_path(r'^celula/listar/agregar/detalle/(?P<pk>\d+)$', views.miembros_celula_list , name='miembros_celula_listar'),
    re_path(r'^celula/listar/agregar/detalle/baja/listar/(?P<pk>\d+)$', views.miembros_celula_list_baja , name='miembros_celula_listar_baja'),
    re_path(r'^celula/listar/agregar/detalle/baja/(?P<pk>\d+)$', views.miembros_celula_delete , name='miembros_celula_eliminar'),
    re_path(r'^celula/listar/agregar/detalle/baja/restaurar/(?P<pk>\d+)$', views.miembros_celula_restore , name='miembros_celula_restaurar'),
	re_path(r'^celula/listar/baja/$', views.celula_list_baja , name='celula_listar_baja'),
	re_path(r'^celula/restaurar/(?P<pk>\d+)/$', views.celula_restore , name='celula_restaurar'),
    re_path(r'^celula/buscardiacelula/$', views.buscar_dia_celula, name='buscardiacelula'),
    re_path(r'^celula/buscarencargadocelula/$', views.buscar_encargado_celula, name='buscarencargadocelula'),
]

apps/celula/models.py
from django.db import models

# Create your models here.
from apps.persona.models import Persona

dias_semana_choices = (
    ('Lunes', 'Lunes'),
    ('Martes', 'Martes'),
    ('Miércoles', 'Miércoles'),
    ('Jueves', 'Jueves'),
    ('Viernes', 'Viernes'),
    ('Sábado', 'Sábado'),
    ('Domingo', 'Domingo'),
)

class Celula(models.Model):
    dia_celula = models.CharField(max_length=10, blank=False, choices = dias_semana_choices)
    hora_celula = models.TimeField(null=True, blank=False)
    direccion_celula = models.CharField(max_length=50, blank=False)
    encargado_celula = models.ForeignKey(Persona, null=False, blank=False, related_name = 'encargado_celula', on_delete=models.CASCADE)
    miembros_celula = models.ManyToManyField(Persona, through='MiembrosCelula')
    fecha_baja_celula = models.DateField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.direccion_celula

    class Meta:
                permissions = (('ver_detalle_celula', 'Ver detalle celulas'),)
                unique_together = (('dia_celula','hora_celula','encargado_celula',),('dia_celula','hora_celula','direccion_celula',))

    def unique_error_message(self, model_class, unique_check):
        error = super().unique_error_message(model_class, unique_check)
        # Intercept the unique_together error
        if len(unique_check) != 1:
            error.message = 'Encargado o dirección no disponible en este día y horario.'
            return error

class MiembrosCelula(models.Model):
    miembro =  models.ForeignKey(Persona, on_delete=models.CASCADE)
    celula = models.ForeignKey(Celula, on_delete=models.CASCADE)
    fecha_ingreso = models.CharField(max_length=30)
    comentario = models.CharField(max_length=10, blank=True, null=True)
    fecha_baja_miembro_celula = models.DateField(max_length=10, blank=True, null=True)

    def __str__(self):
        return self.miembro

    class Meta:
                permissions = (('ver_detalle_miembros_celula', 'Ver detalle miembos de celulas'),)
                unique_together = ("miembro","celula"),

apps/celula/forms.py
from django import forms

from apps.celula.models import Celula, MiembrosCelula, Persona

class CelulaForm(forms.ModelForm):
    encargado_celula = forms.ModelChoiceField(queryset=Persona.objects.filter(fecha_baja_persona__isnull=True))
    def __init__(self, *args, **kwargs):
        super(CelulaForm, self).__init__(*args, **kwargs)
        self.fields['encargado_celula'].label = "Encargado"
    class Meta:
        model = Celula

        fields = [
            'dia_celula',
            'hora_celula',
            'direccion_celula',
            'encargado_celula',
        ]
        labels = {
            'dia_celula': 'Dia',
            'hora_celula': 'Hora',
            'direccion_celula': 'Dirección',
            'encargado_celula': 'Encargado',
        }

class MiembrosCelulaForm(forms.ModelForm):
    miembro = forms.ModelChoiceField(queryset=Persona.objects.filter(fecha_baja_persona__isnull=True))
    def __init__(self, *args, **kwargs):
        super(MiembrosCelulaForm, self).__init__(*args, **kwargs)
        self.fields['miembro'].label = "Miembro"
        self.fields['celula'].label = "Celula"

    class Meta:
        model = MiembrosCelula

        fields = [
            'celula',
            'miembro',
            'fecha_ingreso',
            'comentario',
        ]
        labels = {
            'celula': 'Celula',
            'miembro': 'Miembro',
            'fecha_ingreso': 'Fecha de ingreso',
            'comentario': 'Comentario',
        }

apps/celula/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
import datetime
from apps.celula.forms import CelulaForm, MiembrosCelulaForm
from .models import Celula, MiembrosCelula
from django.db.models import Q
from django.contrib.auth.decorators import login_required

@login_required
def celula_view(request):
    if request.method == 'POST':
        form = CelulaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('celula:celula_listar')
    else:
        form = CelulaForm
    return render(request, 'celula/celula_form.html', {'form':form})

@login_required
def celula_list(request):
	celula = Celula.objects.filter(fecha_baja_celula__isnull=True)
	contexto = {'celulas':celula}
	return render(request, 'celula/celula_listar.html', contexto)

@login_required
def get_queryset_celula(self):
    queryset = Celula.objects.filter(fecha_baja_celula__isnull=True).order_by('hora_celula')
    return queryset

@login_required
def celula_list_baja(request):
	celula = Celula.objects.filter(fecha_baja_celula__isnull=False)
	contexto = {'celulas':celula}
	return render(request, 'celula/celula_listar_baja.html', contexto)

@login_required
def celula_edit(request, pk):
    celula = Celula.objects.get(id=pk)
    if request.method == 'GET':
        form = CelulaForm(instance=celula)
    else:
        form = CelulaForm(request.POST, instance=celula)
        if form.is_valid():
            form.save()
            return redirect('celula:celula_listar')
    return render(request,'celula/celula_form.html',{'form':form})

@login_required
def celula_delete(request, pk):
    celula = Celula.objects.get(id=pk)
    if request.method == 'POST':
	    celula.fecha_baja_celula = datetime.date.today()
	    celula.save()
	    return redirect('celula:celula_listar')
    return render(request,'celula/celula_delete.html',{'celula':celula})

@login_required
def celula_restore(request, pk):
	celula = Celula.objects.get(id=pk)
	if request.method == 'GET':
		celula.fecha_baja_celula = None
		celula.save()
		return redirect('celula:celula_listar_baja')
	return redirect('celula:celula_listar')

@login_required
def buscar_dia_celula(request):
    query = request.GET.get('q')
    if query is not None and query != ' ' and request.is_ajax():
        celulas = get_queryset_celula(request).filter(dia_celula__icontains=query)
        return render(request, 'celula/buscar_celula.html', {'celulas': celulas})
    celulas =  get_queryset_celula(request)
    return render(request, 'celula/buscar_celula.html', {'celulas': celulas})

@login_required
def buscar_encargado_celula(request):
    query = request.GET.get('q')
    if query is not None and query != ' ' and request.is_ajax():
        celulas = get_queryset_celula(request).filter(Q(encargado_celula__nombre__icontains=query)|Q(encargado_celula__apellido_persona__icontains=query))
        return render(request, 'celula/buscar_celula.html', {'celulas': celulas})
    celulas =  get_queryset_celula(request)
    return render(request, 'celula/buscar_celula.html', {'celulas': celulas})

#MIEMBROS
@login_required
def celula_agregar_miembros(request):
	if request.method == 'POST':
		form = MiembrosCelulaForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('celula:celula_agregar_miembros')
	else:
		form = MiembrosCelulaForm
	return render(request, 'celula/celula_agregar_miembros.html', {'form':form})

@login_required
def miembros_celula_list(request, pk):
	miembro_celula = MiembrosCelula.objects.filter(celula_id=pk, fecha_baja_miembro_celula__isnull=True)
	celula = Celula.objects.filter(id=pk)
	contexto = {'miembros_celula':miembro_celula,
				'celulas':celula}
	return render(request, 'celula/miembros_celula_listar.html', contexto)

@login_required
def miembros_celula_list_baja(request, pk):
	miembro_celula = MiembrosCelula.objects.filter(celula_id=pk, fecha_baja_miembro_celula__isnull=False)
	contexto = {'miembros_celula':miembro_celula}
	return render(request, 'celula/miembros_celula_listar_baja.html', contexto)

@login_required
def miembros_celula_delete(request, pk):
    miembro_celula = MiembrosCelula.objects.get(id=pk)
    if request.method == 'POST':
	    miembro_celula.fecha_baja_miembro_celula = datetime.date.today()
	    miembro_celula.save()
	    return redirect('celula:miembros_celula_listar', miembro_celula.celula_id)
    return render(request,'celula/miembros_celula_delete.html',{'miembros_celula':miembro_celula})

@login_required
def miembros_celula_restore(request, pk):
    miembro_celula = MiembrosCelula.objects.get(id=pk)
    if request.method == 'GET':
        miembro_celula.fecha_baja_miembro_celula = None
        miembro_celula.save()
        return redirect('celula:miembros_celula_listar_baja', miembro_celula.celula_id)
    return redirect('celula:miembros_celula_listar', miembro_celula.celula_id)
#
@login_required
class BuscarView(TemplateView):
	def post(self, request, *args, **kwargs):
		buscar = request.POST['buscalo']
		cel1 = Celula.objects.filter(dia_celula__icontains=buscar)
		cel2 = Celula.objects.filter(hora_celula__icontains=buscar)
		cel3 = Celula.objects.filter(direccion_celula__icontains=buscar)
		cel4 = Celula.objects.filter(encargado_celula__nombre__icontains=buscar)
		contexto = {
		'celulas1':cel1,
		'celulas2':cel2,
		'celulas3':cel3,
		'celulas4':cel4,
		}
		return render(request,'celula/buscar.html', contexto)

templates/celula/buscar_celula.html
{% if celulas %}
  {% for celula in celulas %}
    <tr>
      <td>{{ celula.dia_celula }}</td>
      <td>{{ celula.hora_celula }}</td>
      <td>{{ celula.direccion_celula }}</td>
      <td>{{ celula.encargado_celula }}</td>
      {%block campobajacelula%}
      {%endblock%}
      <td>
        {% if celula.fecha_baja_celula == null %}
          {% if perms.celula.change_celula %}
            <a class="btn btn-primary" style="width: 80px; line-height: 5px;padding: 10px;" href="{% url 'celula:celula_editar' celula.id%}">Editar</a>
          {% endif %}
          {% if perms.celula.delete_celula %}
            <a class="btn btn-danger" style="width: 80px; line-height: 5px;padding: 10px;" href="{% url 'celula:celula_eliminar' celula.id%}">Eliminar</a>
          {% endif %}
            <a class="btn btn-default" style="width: 120px; line-height: 5px;padding: 10px;" href="{% url 'celula:miembros_celula_listar' celula.id%}">Ver miembros</a>
            <a class="btn btn-default"style="width: 180px; line-height: 5px;padding: 10px;"  href="{% url 'celula:miembros_celula_listar_baja' celula.id%}">Ver  registros eliminados</a>
        {%endif%}
        {%block pruebacelula%}
        {%endblock%}
      </td>
    </tr>
  {% endfor %}
{% else %}
  <td colspan="13">
    No hay células
  </td>
{% endif %}

templates/celula/celula_delete.html
{% extends 'base/base.html' %}

{% block content %}
{% if perms.celula.delete_celula %}
	<form style="margin: 80px auto auto 20px" method="post">
		{% csrf_token %}
		<h3>¿Desea eliminar la celula de {{ celula.encargado_celula}}?</h3>
		<button class="btn btn-danger" style="line-height: 15px" type="submit">Sí, eliminar</button>
		<a class= "btn btn-default" style="line-height: 15px" href="{% url 'celula:celula_listar' %}">Cancelar</a>
	</form>
{% endif %}
{% endblock %}

templates/celula/celula_form.html
{% extends 'base/base.html' %}

{% block title %}
	Células
{% endblock %}

{% block content %}
{% if perms.celula.add_celula %}
<h2>Registrar célula:</h2>
	<div class="mb-2">
		<form autocomplete="off" method="post">
			{% csrf_token %}
			{% include 'includes/form.html' %}
			<div style="float: left; margin: 27px 17px;">
				<button class="btn btn-success" style="line-height: 15px" type="submit">Registrar</button>
				<a class="btn btn-danger" style="line-height: 15px" href="{% url 'celula:celula_listar' %}">Cancelar</a>
		</div>
		</form>
	</div>
{% endif %}
{% endblock %}

{% block extrajs %}
<script>

	 $('#id_hora_celula').timepicker({
		 showMeridian: false,
		 defaultTime: '00:00',
	 }
	 );
</script>
{% endblock %}

templates/celula/celula_listar.html
{% extends 'base/base.html' %}
{% block title %}
	Detalle de Celulas
{% endblock %}

{% block content %}

<!--boton buscar ---->
<!--
<div class = "busqueda">
	<form class = "navbar-search pull-left" method
	="POST" action="/celula/buscar/">{% csrf_token %}

		<input type="text" name="buscalo" class="search-query"
		placeholder="Buscar">
		<div class="btn-group">
				<button class="btn btn-primary" type
				="sumbit"><i class="icon-search"></i
				></button>
		</div>
	</form>
</div>
<!--fin boton buscar ---->
{%block encabezado%}
	<h2>Células:</h2>
{%endblock%}
{%block buscadorcelula %}
<div id="contenedor">
<th>Buscar: </th>
			<input class="form-control-sm" id="buscar-dia" type="text" placeholder="Dia"/>
      <input class="form-control-sm" id="buscar-encargado" type="text" placeholder="Encargado"/>
</div>
{%endblock%}<h1></h1>
<table  id="contenedor"class="table table-bordered table-hover">
	<thead>
		<tr>
			<th>Dia</th>
			<th>Hora</th>
			<th>Direccion</th>
			<th>Encargado</th>
			{%block titulobaja%}
			{%endblock%}
			<th>Opciones</th>
		</tr>
	</thead>
	<tbody id="resultado-busqueda">
	</tbody>
	<tbody id="main">
		{% if celulas %}
		{% for celula in celulas %}
		<tr>
			<td>{{ celula.dia_celula |title }}</td>
			<td>{{ celula.hora_celula }}</td>
			<td>{{ celula.direccion_celula |title }}</td>
			<td>{{ celula.encargado_celula|title  }}</td>
			{%block campobajacelula%}
			{%endblock%}
			<td>
				{% if celula.fecha_baja_celula == null %}
					{% if perms.celula.change_celula %}
						<a class="btn btn-primary" style="width: 80px; line-height: 5px;padding: 10px;" href="{% url 'celula:celula_editar' celula.id%}">Editar</a>
					{% endif %}
					{% if perms.celula.delete_celula %}
						<a class="btn btn-danger" style="width: 80px; line-height: 5px;padding: 10px;" href="{% url 'celula:celula_eliminar' celula.id%}">Eliminar</a>
					{% endif %}
						<a class="btn btn-default" style="width: 120px; line-height: 5px;padding: 10px;" href="{% url 'celula:miembros_celula_listar' celula.id%}">Ver miembros</a>
						<a class="btn btn-default" style="width: 180px; line-height: 5px;padding: 10px;" href="{% url 'celula:miembros_celula_listar_baja' celula.id%}">Ver  registros eliminados</a>
				{%endif%}
				{%block pruebacelula%}
				{%endblock%}
			</td>
		</tr>
		{% endfor %}
	{% else %}
		<td colspan="13">
			No hay células
		</td>
	{% endif %}
</tbody>
</table>
<ul id="contenedor"class="pager">
	<li>
		{% if page_obj.has_previous %}
			 <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
		{% endif %}
	</li>
	<li>
		{% if page_obj.has_next %}
			<a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
		{% endif %}
	</li>
</ul>
{% block botonfinalcelula %}
	{% if perms.celula.delete_celula %}
		<a id="contenedor"class="btn btn-danger" style="line-height: 15px" href="{% url 'celula:celula_listar_baja' %}">Ver  registros eliminados</a>
	{%endif%}
	{% if perms.celula.add_celula %}
		<a class="btn btn-default" style="line-height: 15px" href="{% url 'celula:celula_agregar_miembros'%}">Agregar miembros</a>
		{%endif%}
{%endblock%}
{% endblock%}

{% block extrajs %}
<script>
$('#buscar-dia').keyup(function (event) {
	var query =($('#buscar-dia').val());
	if ( $.trim( $('#buscar-dia').val() ) != '' ) {
		ajax(query,"buscardiacelula/");
		esconderMain();
	}
	else {
		mostrarMain();
	}
});

$('#buscar-encargado').keyup(function (event) {
	var query =($('#buscar-encargado').val());
	if ( $.trim( $('#buscar-encargado').val() ) != '' ) {
		ajax(query,"buscarencargadocelula/");
		esconderMain();
	}
	else {
		mostrarMain();
	}
});


function mostrarMain(){
$('#resultado-busqueda').hide();
$('#main').show("slow");
}
function esconderMain(){
$('#resultado-busqueda').show("slow");
$('#main').hide();
}

function ajax(query,url){
console.log(query);
$.ajax({
	 type: 'GET',
	 url: url,
	 data: {
		 'csrfmiddlewaretoken': '{{ csrf_token }}',
		 'q': query,
	 },
	 success: function(data) {
		 console.log(data);
			$('#resultado-busqueda').html(data);
	 },
	 error: function(data) {
			console.log(data);
	 }
 });
}

</script>

{% endblock %}

templates/celula/celula_listar_baja.html
{% extends 'celula/celula_listar.html' %}
{% if perms.celula.delete_celula %}

	{%block encabezado%}
		<h2 style="margin: 80px auto auto 20px" >Células dadas de baja:</h2>
	{%endblock%}

	{%block titulobaja%}
		<th>Fecha Baja</th>
	{%endblock%}

	{%block campobajacelula%}
		<td>{{ celula.fecha_baja_celula }}</td>
	{%endblock%}

	{%block pruebacelula%}
		<a class="btn btn-primary" style="line-height: 15px" href="{% url 'celula:celula_restaurar' celula.id%}">Restaurar</a>
	{%endblock%}

	{% block botonfinalcelula %}
		<a id="contenedor" class="btn btn-default" style="line-height: 15px" href="{% url 'celula:celula_listar' %}">Volver</a>
	{% endblock%}

	{%block buscadorcelula %}
	{% endblock%}
{% endif %}

templates/celula/miembros_celula_listar_baja.html
{% extends 'celula/miembros_celula_listar.html' %}

{%block encabezado%}
	<h2 id="contenedor">Miembros dados de baja:</h2>
{%endblock%}

{%block titulobaja%}
	<th>Fecha Baja</th>
{%endblock%}

{%block campobajamiembrocelula%}
	<td>{{ miembro.fecha_baja_miembro_celula }}</td>
{%endblock%}

{%block pruebamiembrocelula%}
{% if perms.celula.change_celula %}
<a class="btn btn-primary" style="line-height: 15px" href="{% url 'celula:miembros_celula_restaurar' miembro.id%}">Restaurar</a>
{% endif %}
{%endblock%}
{%block pruebamiembrocelulabaja%}
<td colspan="13">
	No hay miembros
</td>
{%endblock%}

{%block botonfinalmiembrocelula %}
<a id="contenedor" class="btn btn-default" style="line-height: 15px" href="{% url 'celula:celula_listar'%}">Volver</a>
{% endblock%}

{%block buscadorcelula %}
{% endblock%}