Sistema_Iglesia/urls.py
from django.urls import include, path, re_path, reverse_lazy
from django.contrib import admin
admin.site.site_url = '/portada/index'
from django.contrib.auth import views
from apps.persona import views
from apps.ministerio import views
from apps.usuario import views
from apps.evento import views
from apps.movimiento_dinero import views
from apps.celula import views
from apps.discipulado import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetView, PasswordResetCompleteView, PasswordResetConfirmView, PasswordChangeView, PasswordChangeDoneView, PasswordResetDoneView #login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from apps.usuario.views import RegistroUsuario
from apps.portada import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'authapp'

urlpatterns = [
    #url(r'^admin/', admin.site.urls, name='administrar'),
    re_path(r'^admin/', admin.site.urls, name='administrar'),
    re_path(r'^persona/', include(('apps.persona.urls', 'persona'), namespace='persona')),
    #url(r'^matrimonio/', include('apps.persona.urls', namespace='matrimonio')),
    re_path(r'^movimiento/', include(('apps.movimiento_dinero.urls', 'movimiento_dinero'), namespace='movimiento')),
    #url(r'^categoria/', include('apps.movimiento_dinero.urls', namespace='categoria')),
    re_path(r'^ministerio/', include(('apps.ministerio.urls', 'ministerio'), namespace='ministerio')),
    re_path(r'^evento/', include(('apps.evento.urls', 'evento'), namespace='evento')),
    re_path(r'^celula/', include(('apps.celula.urls', 'celula'), namespace='celula')),
    re_path(r'^articulo/', include(('apps.inventario.urls', 'inventario'), namespace='articulo')),
    #url(r'^unidad_de_medida/', include('apps.inventario.urls', namespace='unidad_de_medida')),
    re_path(r'^entrada/', include(('apps.entrada.urls', 'entrada'), namespace='entrada')),
    re_path(r'^salida/', include(('apps.salida.urls', 'salida'), namespace='salida')),
    re_path(r'^entradasalida/', include(('apps.entradasalida.urls', 'entradasalida'), namespace='entradasalida')),
    re_path(r'^portada/', include(('apps.portada.urls', 'portada'), namespace='portada')),
    re_path(r'^discipulado/', include(('apps.discipulado.urls', 'discipulado'), namespace='discipulado')),
    re_path(r'^portada/', include(('apps.portada.urls','portada'), namespace='portada')),
    re_path(r'^usuario/', include(('apps.usuario.urls', 'usuario'), namespace='usuario')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
#    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'), -----Django 1.8
#    url(r'^logout/', logout_then_login, name='logout'),
    #re_path(r'^accounts/login/$', LoginView.as_view(template_name='index.html'), name='login'), #-----Django 3.1.4
    #re_path(r'^logout/$', LogoutView.as_view(), name='logout'), #-----Django 3.1.4

    re_path(r'^accounts/login/$', LoginView.as_view(template_name='index.html'), name='login'),
    re_path(r'^accounts/logout/$', LogoutView.as_view(template_name='portada/post_list.html'), name='logout'),
    re_path(r'^password_change/', PasswordChangeView.as_view(
        template_name='registration/password_change_form.html'), name='password_change'),
    re_path(r'^password_change/done/', PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),
    re_path(r'^reset/password_reset', PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        email_template_name='registration/password_reset_email.html'), name='password_reset'),
    re_path(r'^password_reset_done', PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'), name='password_reset_done'),

    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',), name='password_reset_confirm'),

    re_path(r'^reset/done', PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'), name='password_reset_complete'),




    #url(r'^password/recovery/',
	#	RegistroUsuario.as_view(
	#		template_name='restration/password_reset_form.html',
	#		email_template_name='restration/password_reset_email.html',
	#	),
	#	name='password_reset',
	#	),
#    re_path(r'^reset/password_reset', PasswordResetView.as_view(),
#        {'template_name':'registration/password_reset_form.html',
#        'email_template_name': 'registration/password_reset_email.html'},
#        name='password_reset'),

#    re_path(r'^password_reset_done', PasswordResetDoneView.as_view(),
#        {'template_name': 'registration/password_reset_done.html'},
#        name='password_reset_done'),

#    re_path(r'^password/recovery/(?P<uidb64>[0-9A-Za-z_\-]+)/'
#        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', PasswordResetConfirmView.as_view(),
#        {'template_name': 'registration/password_reset_confirm.html'},
#        name='password_reset_confirm'),

    # url(
    #    r'^password/recovery/(?P<uidb64>[0-9A-Za-z_\-]+)/'
    #    r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #    auth_views.PasswordResetConfirmView.as_view(
    #        success_url=reverse_lazy('home'),
    #        post_reset_login=True,
    #        template_name='registration/password_reset_confirm.html',
    #        post_reset_login_backend=(
    #            'django.contrib.auth.backends.AllowAllUsersModelBackend'
    #        ),
    #    ),
    #    name='password_reset_confirm',
    #),

#    re_path(r'^reset/done', PasswordResetCompleteView, {'template_name': 'registration/password_reset_complete.html'},
#        name='password_reset_complete'),




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/portada/urls.py
from django.urls import include, path, re_path
from apps.portada import views

urlpatterns = [

    re_path(r'^index$',views.video, name='post_list'), #views.post_list
    re_path('post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    re_path('post/new/', views.post_new, name='post_new'),
    re_path('post/post_new_borrador/', views.post_new_borrador, name='post_new_borrador'),
    re_path('post/editar/(?P<pk>\d+)/$', views.post_edit, name='post_edit'),
    re_path('post/borrador/$', views.post_draft_list, name='post_draft_list'),
    re_path(r'^post/(?P<pk>\d+)/publicar/$', views.post_publish, name='post_publish'),
    re_path(r'^post/(?P<pk>\d+)/borrar/$', views.post_remove, name='post_remove'),


]

apps/portada/models.py
from django.db import models
from django.utils import timezone
#from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from embed_video.fields import EmbedVideoField

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
#    text = RichTextUploadingField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Item(models.Model):
    video = EmbedVideoField()  # same like models.URLField()

apps/portada/forms.py
from django import forms
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from .models import Post

class PostForm(forms.ModelForm):
    text = forms.CharField(widget=CKEditorUploadingWidget())

    class Meta:
        model = Post

        fields = ['title', 'text',]
        labels = {
            'title': 'Título',
            'text': 'Contenido',}

apps/portada/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Item, Post
from django.shortcuts import render, get_object_or_404
#from .forms import PostForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required


def video(request):
    obj = Item.objects.all()
    return render(request, 'portada/post_list.html', {'obj': obj})

#@login_required
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'portada/post_list.html', {'posts': posts})

@login_required
def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk)
    return render(request, 'portada/post_detail.html', {'post': post})

@login_required
def post_new_borrador(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('portada.views.post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'portada/post_edit_borrador.html', {'form': form})

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('portada.views.post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'portada/post_edit.html', {'form': form})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('portada:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'portada/post_edit.html', {'form': form})

@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'portada/post_draft_list.html', {'posts': posts})

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('portada:post_list')#'portada:post_detail', pk=pk)

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('portada:post_list')

templates/portada/post_detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">
<!--<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">-->
<link href="//fonts.googleapis.com/css?family=Comfortaa:400,700&subset=latin,latin-ext" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <div class="post">
      {% if post.published_date %}
        <div class="date">
          {{ post.published_date }}
        </div>
      {% else %}
        <a class="btn btn-default" style="line-height: 15px" href="{% url 'portada:post_publish' pk=post.pk %}">Publicar <span class="glyphicon glyphicon-share-alt"></span></a>
      {% endif %}
        {% if user.is_authenticated %}
          <a class="btn btn-default" style="line-height: 15px" href="{% url 'portada:post_edit' post.id %}">Editar <span class="glyphicon glyphicon-pencil"></span></a>
          <a class="btn btn-default" style="line-height: 15px" href="{% url 'portada:post_remove' pk=post.pk %}">Eliminar <span class="glyphicon glyphicon-remove"></span></a>
        {% endif %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|safe  }}</p>
    </div>
<a class="btn btn-default" style="line-height: 15px" href="{% url 'portada:post_list' %}">Volver a la página principal</a>
{% endblock %}

templates/portada/post_draft_list.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<title>Borrador</title>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">
<!--<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">-->
<link href="//fonts.googleapis.com/css?family=Comfortaa:400,700&subset=latin,latin-ext" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="{% static 'css/blog.css' %}">
<!--<h1><a href="/">Borradores:</a></h1>-->
<h1>Borradores:</h1>
{% if posts %}
    {% for post in posts %}
        <div class="post">
            <p class="date"> {{ post.created_date|date:'Y-m-d H:i:s' }}</p>
            <h1><a href="{% url 'portada:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|safe }}</p>
        </div>
    {% endfor %}
{% else %}
  <p>No hay publicaciones</p>
{% endif %}
<a class="btn btn-primary" style="line-height: 15px" href="{% url 'portada:post_new_borrador'%}">Crear borrador</a>
<a class="btn btn-default" style="line-height: 15px" href="{% url 'portada:post_list' %}">Volver a la página principal</a>
{% endblock %}

templates/portada/post_edit.html
{% extends 'base/base.html' %}
{% load static %}
{% load wysiwyg %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">
<!--<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">-->
<link href="//fonts.googleapis.com/css?family=Comfortaa:400,700&subset=latin,latin-ext" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <a class="btn btn-default" style="float: right; line-height: 15px;" href="{% url 'portada:post_list'%}">Volver a la página principal</a>
<h1>Nueva Publicación</h1>
<form autocomplete="off" method="POST" class="post-form">{% csrf_token %}

    {{ form.media }}
    {{ form.as_p }}
    <!--<button type="reset" class="save btn btn-default">Reiniciar</button>-->
    <!--<a class="btn btn-primary " href="{% url 'portada:post_new_borrador'%}">Crear borrador</a>-->
    <a class="btn btn-default" style="line-height: 15px" href="{% url 'portada:post_draft_list' %}">Ver borradores</a>
    <button type="submit" class="save btn btn-danger" style="line-height: 15px" >Publicar <span class="glyphicon glyphicon-share-alt"></span></button>
</form>

{% endblock %}

templates/portada/post_edit_borrador.html
{% extends 'base/base.html' %}
{% load static %}
{% load wysiwyg %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">
<!--<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">-->
<link href="//fonts.googleapis.com/css?family=Comfortaa:400,700&subset=latin,latin-ext" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="{% static 'css/blog.css' %}">

<h1>Nuevo Borrador</h1>
<form autocomplete="off" method="POST" class="post-form">{% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Guardar</button>
    <!--<button type="reset" class="save btn btn-default">Reset</button>-->
    <a class="btn btn-default" style="line-height: 15px" href="{% url 'portada:post_list' %}">Volver a la página principal</a>
    <a class="btn btn-default" style="line-height: 15px" href="{% url 'portada:post_draft_list' %}">Ver borradores</a>
</form>

{% endblock %}

templates/portada/post_list_original.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}
<html>
    <head>
        <title>Sistema Iglesia</title>

        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
          <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        </head>


        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">
    <!--  <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">-->
          <link href="//fonts.googleapis.com/css?family=Comfortaa:400,700&subset=latin,latin-ext" rel="stylesheet" type="text/css">
          <link rel="stylesheet" href="{% static 'css/blog.css' %}">
          <style>
            body {
              background-image: url("../media/imagenes/clouds-1209444_19202.jpg");
              background-repeat: no-repeat;
              background-size: cover;
              background-attachment: fixed;
            }
            img {
              display: block;
              margin-left: auto;
              margin-right: auto;
              width: 15%;
            }
          </style>
    </head>

<body>
	<div class="contenedor">
		<br>
		<div class="col-md-12">
			<div id="carousel-1" class="carousel slide" data-ride="carousel">
				<!-- Indicadores -->

				<!-- contenedor de los slide -->

					<!-- #1 -->
					<div class="banner">
					 	<img src="../media/imagenes/ijme.negro.png" class="img-responsive" >   <!-- YA ME QUEDO CLARO POR QUE TODAS LAS IMAGENES MISMO TAMAÑO -->
              {% if user.is_authenticated %}
              <h1>Publicaciones: </h1>
              {% if perms.portada.add_post or perms.portada.change_post or perms.portada.delete_post %}
                <a href="{% url 'portada:post_new' %}" class="top-menu" title="Nueva publicación"><span class="glyphicon glyphicon-plus" style="color:black"></span></a>
                <a href="{% url 'portada:post_draft_list' %}" class="top-menu" title="Borradores"><span class="glyphicon glyphicon-edit" style="color:black"></span></a>
              {% endif %}
              {% endif %}
							<!-- <h3>Este es nuestro Slide #1</h3>
							<p>Lorem ipsum dolor sit amet.</p> -->
					</div>
		</div>
	</div>
	<script src="jquery-3.2.1.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
</body>

<body>
      <div class="content container">
        <div class="row">
          <div class="col-md-8">
              {% for post in posts %}
                  <div class="post">
                    <!--  <div class="date">
                          {{ post.published_date }}
                      </div>-->
<!--                      <h1><a href="{% url 'portada:post_detail' post.id %}">{{ post.title }}</a></h1>
                        {{ post.published_date }}<!--<p>{{ post.text|safe  }}</p>-->
<!--                  </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </body>
</html>
{% endblock %}