Sistema_Iglesia/urls.py
from django.urls import include, path, re_path, reverse_lazy
from django.contrib import admin
admin.site.site_url = '/portada/index'
from django.contrib.auth import views
from apps.persona import views
from apps.ministerio import views
from apps.usuario import views
from apps.evento import views
from apps.movimiento_dinero import views
from apps.celula import views
from apps.discipulado import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetView, PasswordResetCompleteView, PasswordResetConfirmView, PasswordChangeView, PasswordChangeDoneView, PasswordResetDoneView #login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from apps.usuario.views import RegistroUsuario
from apps.portada import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'authapp'

urlpatterns = [
    #url(r'^admin/', admin.site.urls, name='administrar'),
    re_path(r'^admin/', admin.site.urls, name='administrar'),
    re_path(r'^persona/', include(('apps.persona.urls', 'persona'), namespace='persona')),
    #url(r'^matrimonio/', include('apps.persona.urls', namespace='matrimonio')),
    re_path(r'^movimiento/', include(('apps.movimiento_dinero.urls', 'movimiento_dinero'), namespace='movimiento')),
    #url(r'^categoria/', include('apps.movimiento_dinero.urls', namespace='categoria')),
    re_path(r'^ministerio/', include(('apps.ministerio.urls', 'ministerio'), namespace='ministerio')),
    re_path(r'^evento/', include(('apps.evento.urls', 'evento'), namespace='evento')),
    re_path(r'^celula/', include(('apps.celula.urls', 'celula'), namespace='celula')),
    re_path(r'^articulo/', include(('apps.inventario.urls', 'inventario'), namespace='articulo')),
    #url(r'^unidad_de_medida/', include('apps.inventario.urls', namespace='unidad_de_medida')),
    re_path(r'^entrada/', include(('apps.entrada.urls', 'entrada'), namespace='entrada')),
    re_path(r'^salida/', include(('apps.salida.urls', 'salida'), namespace='salida')),
    re_path(r'^entradasalida/', include(('apps.entradasalida.urls', 'entradasalida'), namespace='entradasalida')),
    re_path(r'^portada/', include(('apps.portada.urls', 'portada'), namespace='portada')),
    re_path(r'^discipulado/', include(('apps.discipulado.urls', 'discipulado'), namespace='discipulado')),
    re_path(r'^portada/', include(('apps.portada.urls','portada'), namespace='portada')),
    re_path(r'^usuario/', include(('apps.usuario.urls', 'usuario'), namespace='usuario')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
#    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'), -----Django 1.8
#    url(r'^logout/', logout_then_login, name='logout'),
    #re_path(r'^accounts/login/$', LoginView.as_view(template_name='index.html'), name='login'), #-----Django 3.1.4
    #re_path(r'^logout/$', LogoutView.as_view(), name='logout'), #-----Django 3.1.4

    re_path(r'^accounts/login/$', LoginView.as_view(template_name='index.html'), name='login'),
    re_path(r'^accounts/logout/$', LogoutView.as_view(template_name='portada/post_list.html'), name='logout'),
    re_path(r'^password_change/', PasswordChangeView.as_view(
        template_name='registration/password_change_form.html'), name='password_change'),
    re_path(r'^password_change/done/', PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),
    re_path(r'^reset/password_reset', PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        email_template_name='registration/password_reset_email.html'), name='password_reset'),
    re_path(r'^password_reset_done', PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'), name='password_reset_done'),

    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',), name='password_reset_confirm'),

    re_path(r'^reset/done', PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'), name='password_reset_complete'),




    #url(r'^password/recovery/',
	#	RegistroUsuario.as_view(
	#		template_name='restration/password_reset_form.html',
	#		email_template_name='restration/password_reset_email.html',
	#	),
	#	name='password_reset',
	#	),
#    re_path(r'^reset/password_reset', PasswordResetView.as_view(),
#        {'template_name':'registration/password_reset_form.html',
#        'email_template_name': 'registration/password_reset_email.html'},
#        name='password_reset'),

#    re_path(r'^password_reset_done', PasswordResetDoneView.as_view(),
#        {'template_name': 'registration/password_reset_done.html'},
#        name='password_reset_done'),

#    re_path(r'^password/recovery/(?P<uidb64>[0-9A-Za-z_\-]+)/'
#        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', PasswordResetConfirmView.as_view(),
#        {'template_name': 'registration/password_reset_confirm.html'},
#        name='password_reset_confirm'),

    # url(
    #    r'^password/recovery/(?P<uidb64>[0-9A-Za-z_\-]+)/'
    #    r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #    auth_views.PasswordResetConfirmView.as_view(
    #        success_url=reverse_lazy('home'),
    #        post_reset_login=True,
    #        template_name='registration/password_reset_confirm.html',
    #        post_reset_login_backend=(
    #            'django.contrib.auth.backends.AllowAllUsersModelBackend'
    #        ),
    #    ),
    #    name='password_reset_confirm',
    #),

#    re_path(r'^reset/done', PasswordResetCompleteView, {'template_name': 'registration/password_reset_complete.html'},
#        name='password_reset_complete'),




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/evento/urls.py
from django.urls import include, path,re_path
from django.contrib.auth.views import login_required
from apps.evento import views
from apps.evento.views import  evento_view, evento_list, evento_edit, \
	  evento_delete, evento_list_baja, evento_restore, buscar_evento_descripcion

urlpatterns = [
    re_path(r'^evento/listar$', views.evento_list, name='evento_listar'),
    re_path(r'^evento/nueva$', views.evento_view, name='evento_crear'),
    re_path(r'^evento/editar/(?P<pk>\d+)$', views.evento_edit, name='evento_editar'),
    re_path(r'^evento/eliminar/(?P<pk>\d+)$', views.evento_delete, name='evento_eliminar'),
	re_path(r'^evento/listar/baja/$', views.evento_list_baja , name='evento_listar_baja'),
	re_path(r'^evento/restaurar/(?P<pk>\d+)/$', views.evento_restore , name='evento_restaurar'),
    re_path(r'^evento/buscarevento/$', views.buscar_evento_descripcion, name='buscarevento'),

]

apps/evento/models.py
from django.db import models

# Create your models here.
class Evento(models.Model):
    descripcion_evento = models.CharField(max_length=200)
    fecha_evento = models.CharField(max_length=10,null=False, blank=False)
    lugar_evento = models.CharField(max_length=30)
    hora_evento = models.TimeField(null=False, blank=False)
    fecha_baja_evento = models.DateField(max_length=50, blank=True, null=True)

    def __str__(self):
        return '{} / {}'.format(self.descripcion_evento,self.fecha_evento)
#    id_evento = models.ForeignKey(Ministerios, null=True, blank=True, on_delete=models.CASCADE) #es asi?
    class Meta:
                permissions = (('ver_detalle_evento', 'Ver detalle eventos'),)

apps/evento/forms.py
from django import forms

from apps.evento.models import Evento

class EventoForm(forms.ModelForm):

    class Meta:
        model = Evento

        fields = [
            'descripcion_evento',
            'fecha_evento',
            'lugar_evento',
            'hora_evento',
            #'id_ministerio_encargado'
        ]
        labels = {
            'descripcion_evento': 'Descripcion:',
            'fecha_evento': 'Dia:',
            'lugar_evento': 'Lugar:',
            'hora_evento': 'Hora:',
        }

apps/evento/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
import datetime
from apps.evento.models import Evento
from apps.evento.forms import EventoForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required
#from apps.persona.models import Persona # en apps\ministerio\views tambien esta

from .models import Evento


@login_required
def evento_view(request):
    if request.method == 'POST':
        form = EventoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('evento:evento_listar')
    else:
        form = EventoForm
    return render(request, 'evento/evento_form.html', {'form':form})

@login_required
def evento_list(request):
	evento = Evento.objects.filter(fecha_baja_evento__isnull=True)
	contexto = {'eventos':evento}
	return render(request, 'evento/evento_listar.html', contexto)

@login_required
def get_queryset_evento(self):
    queryset = Evento.objects.filter(fecha_baja_evento__isnull=True).order_by('descripcion_evento')
    return queryset

@login_required
def evento_list_baja(request):
	evento = Evento.objects.filter(fecha_baja_evento__isnull=False)
	contexto = {'eventos':evento}
	return render(request, 'evento/evento_listar_baja.html', contexto)

@login_required
def evento_edit(request, pk):
    evento = Evento.objects.get(id=pk)
    if request.method == 'GET':
        form = EventoForm(instance=evento)
    else:
        form = EventoForm(request.POST, instance=evento)
        if form.is_valid():
            form.save()
            return redirect('evento:evento_listar')
    return render(request,'evento/evento_form.html',{'form':form})

@login_required
def evento_restore(request, pk):
    evento = Evento.objects.get(id=pk)
    if request.method == 'GET':
        evento.fecha_baja_evento = None
        evento.save()
        return redirect('evento:evento_listar_baja')
    return redirect('evento:evento_listar')

@login_required
def evento_delete(request, pk):
    evento = Evento.objects.get(id=pk)
    if request.method == 'POST':
        evento.fecha_baja_evento = datetime.date.today()
        evento.save()
        return redirect('evento:evento_listar')
    return render(request,'evento/evento_delete.html',{'evento':evento})

@login_required
def buscar_evento_descripcion(request):
    query = request.GET.get('q')
    if query is not None and query != ' ' and request.is_ajax():
        eventos = get_queryset_evento(request).filter(descripcion_evento__icontains=query)
        return render(request, 'evento/buscar_evento.html', {'eventos': eventos})
    eventos =  get_queryset_evento(request)
    return render(request, 'evento/buscar_evento.html', {'eventos': eventos})
#class BuscarView(TemplateView):
#	def post(self, request, *args, **kwargs):
#		buscar = request.POST['buscalo']
#		eve1 = Evento.objects.filter(descripcion_evento__icontains=buscar)
#		eve2 = Evento.objects.filter(fecha_evento__icontains=buscar)
	#	eve3 = Evento.objects.filter(lugar_evento__icontains=buscar)
	#	eve4 = Evento.objects.filter(hora_evento__icontains=buscar)
	#	contexto = {
		#'eventos1':eve1,
		#'eventos2':eve2,
		#'eventos3':eve3,
		#'eventos4':eve4,
		#}
		#return render(request,'evento/buscar.html', contexto)

templates/evento/buscar.html
{% extends 'base/base.html' %}

{% block content %}

<!--boton buscar ---->
<div class = "busqueda">
	<form class = "navbar-search pull-left" method
	="POST" action="/evento/buscar/">{% csrf_token %}

		<input type="text" name="buscalo" class="search-query"
		placeholder="Buscar">
		<div class="btn-group">
				<button class="btn btn-primary" type
				="sumbit"><i class="icon-search"></i
				></button>
		</div>
	</form>
</div>
<!--fin boton buscar ---->

<table class="table table-bordered">
	<thead>
		<tr>
			<th>Descripción</th>
			<th>Fecha</th>
			<th>Lugar</th>
			<th>Hora</th>
		</tr>
	</thead>
	<tbody>
		{% if eventos1 %}
	  {% for eve1 in eventos1 %}
	   <tr>
    	<td>{{ eve1.descripcion_evento }}</td>
    	<td>{{ eve1.fecha_evento }}</td>
			<td>{{ eve1.lugar_evento }}</td>
			<td>{{ eve1.hora_evento }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'evento:evento_editar' eve1.id%}">Editar</a>
				<a class="btn btn-danger" href="{% url 'evento:evento_eliminar' eve1.id%}">Eliminar</a>
		  </td>
     </tr>
	  {% endfor %}
		{% elif eventos2 %}
		{% for eve2 in eventos2 %}
		 <tr>
	   	<td>{{ eve2.descripcion_evento }}</td>
	   	<td>{{ eve2.fecha_evento }}</td>
			<td>{{ eve2.lugar_evento }}</td>
			<td>{{ eve2.hora_evento }}</td>
			<td>
		  	<a class="btn btn-primary" style="line-height: 15px" href="{% url 'evento:evento_editar' eve2.id%}">Editar</a>
				<a class="btn btn-danger" style="line-height: 15px" href="{% url 'evento:evento_eliminar' eve2.id%}">Eliminar</a>
			</td>
	   </tr>
		{% endfor %}
		{% elif eventos3 %}
		{% for eve3 in eventos3 %}
			<tr>
		   <td>{{ eve3.descripcion_evento }}</td>
			 <td>{{ eve3.fecha_evento }}</td>
			 <td>{{ eve3.lugar_evento }}</td>
			 <td>{{ eve3.hora_evento }}</td>
			 <td>
				<a class="btn btn-primary" style="line-height: 15px" href="{% url 'evento:evento_editar' eve3.id%}">Editar</a>
				<a class="btn btn-danger" style="line-height: 15px" href="{% url 'evento:evento_eliminar' eve3.id%}">Eliminar</a>
			 </td>
			</tr>
	  {% endfor %}
		{% elif eventos4 %}
		{% for eve4 in eventos4 %}
			<tr>
		  	<td>{{ eve4.descripcion_evento }}</td>
				<td>{{ eve4.fecha_evento }}</td>
				<td>{{ eve4.lugar_evento }}</td>
				<td>{{ eve4.hora_evento }}</td>
				<td>
					<a class="btn btn-primary" style="line-height: 15px" href="{% url 'evento:evento_editar' eve4.id%}">Editar</a>
					<a class="btn btn-danger" style="line-height: 15px" href="{% url 'evento:evento_eliminar' eve4.id%}">Eliminar</a>
				</td>
			</tr>
		{% endfor %}
    {% else %}
  	<h1>No hay eventos registrados</h1>    <!-- ver esto ---->
  	{% endif %}
  	</tbody>
  </table>
  <ul class="pager">
  	<li>
  		{% if page_obj.has_previous %}
         	 <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>

  		{% endif %}
    </li>
  	<li>
  		{% if page_obj.has_next %}
       	 <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>

      	{% endif %}
    </li>
  </ul>

  {% endblock%}

templates/evento/buscar_evento.html
{% if eventos %}
{% for evento in eventos %}
<tr>
  <td>{{ evento.descripcion_evento }}</td>
  <td>{{ evento.fecha_evento }}</td>
  <td>{{ evento.lugar_evento }}</td>
  <td>{{ evento.hora_evento }}</td>
  {%block campobajaevento%}
  {%endblock%}
  <td>
    {% if evento.fecha_baja_evento == null %}
      {% if perms.evento.change_evento %}
        <a class="btn btn-primary" style="width: 80px; line-height: 5px;padding: 10px;" href="{% url 'evento:evento_editar' evento.id%}">Editar</a>
      {% endif %}
      {% if perms.evento.delete_evento %}
        <a class="btn btn-danger" style="width: 80px; line-height: 5px;padding: 10px;" href="{% url 'evento:evento_eliminar' evento.id%}">Eliminar</a>
      {% endif %}
    {%endif%}
    {%block pruebaevento%}
    {%endblock%}
  </td>
</tr>
{% endfor %}
{% else %}
  <td colspan="13">
    No hay eventos
  </td>
{% endif %}

templates/evento/evento_delete.html
{% extends 'base/base.html' %}

{% block content %}
	{% if perms.evento.delete_evento %}
	<form style="margin: 80px auto auto 20px" method="post">
		{% csrf_token %}
		<h3>¿Desea eliminar el evento {{ evento.descripcion_evento}}?</h3>
		<button class="btn btn-danger" style="line-height: 15px" type="submit">Sí, eliminar</button>
		<a class= "btn btn-default" style="line-height: 15px" href="{% url 'evento:evento_listar' %}">Cancelar</a>
	</form>
	{% endif %}
{% endblock %}

templates/evento/evento_form.html
{% extends 'base/base.html' %}
{% load static %}


{% block title %}
	Eventos
{% endblock %}

{% block content %}
	{% if perms.evento.add_evento %}
	<h2>Registrar evento:</h2>
	<div class="mb-2">
		<form autocomplete="off" method="post">
			{% csrf_token %}
			{% include 'includes/form.html' %}
			<div style="float: left; margin: 27px 17px;">
			<button class="btn btn-success" style="line-height: 15px" type="submit">Registrar</button>
			<a class="btn btn-danger" style="line-height: 15px" href="{% url 'evento:evento_listar' %}">Cancelar</a>
			</div>
		</form>
	</div>
		{% endif %}
{% endblock %}
{% block extrajs %}
<script>

$('#id_fecha_evento').datepicker({
		todayBtn: "linked",
		format: 'dd-mm-yyyy',
		startDate: '1d',
		language: 'es',
		autoclose: true,
	});

$('#id_hora_evento').timepicker({
		showMeridian: false,
		defaultTime: '00:00',
	});
</script>

{% endblock %}

templates/evento/evento_listar.html
{% extends 'base/base.html' %}
{% block title %}
	Detalle de Eventos
{% endblock %}

{% block content %}

<!--boton buscar ---->
<!--
<div class = "busqueda">
	<form class = "navbar-search pull-left" method
	="POST" action="/evento/buscar/">{% csrf_token %}

		<input type="text" name="buscalo" class="search-query"
		placeholder="Buscar">
		<div class="btn-group">
				<button class="btn btn-primary" type
				="sumbit"><i class="icon-search"></i
				></button>
		</div>
	</form>
</div>
<!--fin boton buscar ---->
{%block encabezado%}
	<h2>Eventos:</h2>
{%endblock%}
{% block buscadorevento %}
<div id="contenedor" >
	<th>Buscar: </th>
			<input class="form-control-sm" id="buscar-eventos" type="text" placeholder="Descripción"/>
</div>
{%endblock%}<h1></h1>
<table id="contenedor" class="table table-bordered table-hover">
	<thead>
		<tr>
			<th>Descripción</th>
			<th>Fecha</th>
			<th>Lugar</th>
			<th>Hora</th>
			{%block titulobajaevento%}
			{%endblock%}
			<th>Opciones</th>
		</tr>
	</thead>
	<tbody id="resultado-busqueda">
	</tbody>
	<tbody id="main">
		{% if eventos %}
		{% for evento in eventos %}
		<tr>
			<td>{{ evento.descripcion_evento |capfirst }}</td>
			<td>{{ evento.fecha_evento }}</td>
			<td>{{ evento.lugar_evento |capfirst}}</td>
			<td>{{ evento.hora_evento }}</td>
			{%block campobajaevento%}
			{%endblock%}
			<td>
				{% if evento.fecha_baja_evento == null %}
					{% if perms.evento.change_evento %}
						<a class="btn btn-primary" style="width: 80px; line-height: 5px;padding: 10px;" href="{% url 'evento:evento_editar' evento.id%}">Editar</a>
					{% endif %}
					{% if perms.evento.delete_evento %}
						<a class="btn btn-danger" style="width: 80px; line-height: 5px;padding: 10px;" href="{% url 'evento:evento_eliminar' evento.id%}">Eliminar</a>
					{% endif %}
				{%endif%}
				{%block pruebaevento%}
				{%endblock%}
			</td>
		</tr>
		{% endfor %}
		{% else %}
			<td colspan="13">
				No hay eventos
			</td>
		{% endif %}
	</tbody>
</table>
<ul id="contenedor" class="pager">
	<li>
		{% if page_obj.has_previous %}
       	 <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
		{% endif %}
  </li>
	<li>
		{% if page_obj.has_next %}
     	 <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
    {% endif %}
  </li>
</ul>
{% block botonfinalevento %}
	{% if perms.evento.delete_evento %}
		<a id="contenedor" class="btn btn-danger" style="line-height: 15px" href="{% url 'evento:evento_listar_baja' %}">Ver  registros eliminados</a>
	{%endif%}
{%endblock%}
{% endblock%}

{% block extrajs %}
<script>
	$('#buscar-eventos').keyup(function (event) {
	  var query =($('#buscar-eventos').val());
	  if ( $.trim( $('#buscar-eventos').val() ) != '' ) {
			ajax(query,"buscarevento/");
			esconderMain();
	  }
	  else {
			mostrarMain();
	  }
	});

function mostrarMain(){
	$('#resultado-busqueda').hide();
	$('#main').show("slow");
}
function esconderMain(){
	$('#resultado-busqueda').show("slow");
	$('#main').hide();
}

function ajax(query,url){
	console.log(query);
	$.ajax({
		 type: 'GET',
		 url: url,
		 data: {
			 'csrfmiddlewaretoken': '{{ csrf_token }}',
			 'q': query,
		 },
		 success: function(data) {
			 console.log(data);
				$('#resultado-busqueda').html(data);
		 },
		 error: function(data) {
				console.log(data);
		 }
	 });
}

</script>

{% endblock %}

templates/evento/evento_listar_baja.html
{% extends 'evento/evento_listar.html' %}
{% if perms.evento.delete_evento %}

{%block encabezado%}
	<h2>Eventos dados de baja:</h2>
{%endblock%}

{%block titulobajaevento%}
	<th>Fecha Baja</th>
{%endblock%}

{%block campobajaevento%}
	<td>{{ evento.fecha_baja_evento }}</td>
{%endblock%}

{%block pruebaevento%}
	<a class="btn btn-primary" style="line-height: 15px" href="{% url 'evento:evento_restaurar' evento.id%}">Restaurar</a>
{%endblock%}

{% block botonfinalevento %}
	<a id="contenedor" class="btn btn-default" style="line-height: 15px" href="{% url 'evento:evento_listar' %}">Volver</a>
{% endblock%}

{% block buscadorevento %}
{% endblock%}
{% endif %}